"""modified products and users  added price to products

Revision ID: dd272afd1e32
Revises: c374db022785
Create Date: 2023-07-25 22:39:13.479171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd272afd1e32'
down_revision = 'c374db022785'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.DECIMAL(precision=16, scale=4), nullable=False))
    #op.add_column('users', sa.Column('user_name', sa.VARCHAR(length=255), nullable=True))
    #op.drop_column('users', 'username')
    # renamed users column username to user_name
    op.alter_column(
        table_name='users',
        column_name=sa.column(text='username'),
        new_column_name=sa.column(text='user_name')
    )
    # description: Mapped[Optional[str]] = mapped_column(VARCHAR(3000))
    # changed length of varchar from 255 to 3000 characters for description column.
    op.alter_column(
        table_name='products',
        column_name=sa.column(text='description'),
        type_=sa.VARCHAR(length=3000)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # op.drop_column('users', 'user_name')
    op.alter_column(
        table_name='users',
        column_name=sa.column(text='user_name'),
        new_column_name=sa.column(text='username'))
    # change the length of varchar from 3000 to 255 characters for description column.
    op.alter_column(
        table_name='products',
        column_name=sa.column(text='description'),
        type_=sa.VARCHAR(length=255)
    )
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
